name: flutter_qr_code_scanner_generator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  qr_code_scanner: ^1.0.1
  google_ml_kit: ^0.16.3
  image_picker: ^1.0.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

